# Generated by Django 3.1.1 on 2020-09-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('nation', models.CharField(max_length=10)),
                ('del_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=10)),
                ('del_yn', models.BooleanField(default=False)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.country')),
            ],
        ),
    ]
